### ISSUE TITLE
vcf file as output of ivar

### ISSUE THREAD

**Issue by AndreaAguadoM** [LilWinx/Sabres#20]
Hello, my name is Andrea and I am a bioinformatitian from Spain.
I am trying to use SABRes in an analysis I am performing using some Immunocompromised patient samples. As input, I am using a vcf file generated by ivar. Reading the README, I have noticed how tsv is the extention registered as output of ivar. In any case, when executing the line sabres --vcall ivar --input sample.vcf, the output files are empty. Is this because of no resistance mutation has been found, or is it a problem derived of the ivar format specification? 
Thanks in advance!

**Comment by LilWinx** [comment]
Hello, apologies for the delay in response. At the moment only TSV files from iVar are accepted as input. The output will be empty mainly because only TSVs work with the --vcall ivar. The easiest and quickest solution would be use the TSV file instead. I can work on adding ivar vcfs.
