### ISSUE TITLE
Use consensus sequence as input

### ISSUE THREAD

**Issue by Wytamma** [LilWinx/Sabres#9]
Hi @LilWinx! We have Sabres working on BAM files using ivar. I was wondering if you have a way to generate the required input files from a consensus sequence?

**Comment by LilWinx** [comment]
For this, at the moment the only way I can think of is to generate a VCF from a multi-sequence alignment using fatovcf, I can add the output of fatovcf to my list of to-dos if you think it'll be useful for you

**Comment by LilWinx** [comment]
I have added fatovcf to Sabres which is part of the UShER (https://github.com/yatisht/usher) pipeline to allow for Consensus level detection.
